version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: ".github/workflows"

  - package-ecosystem: pip
    directory: /docs
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /test
    schedule:
      interval: daily
